version: "3.9"

services:
    api:
        build:
            context: apps/dashboard
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        networks:
            - next-node

    dashboard:
        build:
            context: apps/dashboard
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        networks:
            - next-node

    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=coldoutreach
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - next-node

networks:
    next-node:

volumes:
    pgdata:
