version: "3.9"

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=coldoutreach
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - next-node

networks:
    next-node:

volumes:
    pgdata:
