/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './tanstack/routes/__root'
import { Route as IndexRouteImport } from './tanstack/routes/index'
import { Route as DashboardIndexRouteImport } from './tanstack/routes/dashboard/index'
import { Route as DashboardCampaignsIndexRouteImport } from './tanstack/routes/dashboard/campaigns/index'
import { Route as DashboardProjectsIndexRouteImport } from './tanstack/routes/dashboard/projects/index'
import { Route as DashboardCampaignsCampaignIdIndexRouteImport } from './tanstack/routes/dashboard/campaigns/$campaignId/index'
import { Route as DashboardCampaignsCampaignIdSettingsRouteImport } from './tanstack/routes/dashboard/campaigns/$campaignId/settings'
import { Route as DashboardLeadsLabelsIndexRouteImport } from './tanstack/routes/dashboard/leads/labels/index'
import { Route as DashboardLeadsListsIndexRouteImport } from './tanstack/routes/dashboard/leads/lists/index'
import { Route as DashboardLeadsListsIdIndexRouteImport } from './tanstack/routes/dashboard/leads/lists/$id/index'
import { Route as DashboardProjectsProjectIdCollaboratorsIndexRouteImport } from './tanstack/routes/dashboard/projects/$projectId/collaborators/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/dashboard/campaigns/',
  path: '/dashboard/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/dashboard/projects/',
  path: '/dashboard/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCampaignsCampaignIdIndexRoute =
  DashboardCampaignsCampaignIdIndexRouteImport.update({
    id: '/dashboard/campaigns/$campaignId/',
    path: '/dashboard/campaigns/$campaignId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCampaignsCampaignIdSettingsRoute =
  DashboardCampaignsCampaignIdSettingsRouteImport.update({
    id: '/dashboard/campaigns/$campaignId/settings',
    path: '/dashboard/campaigns/$campaignId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLeadsLabelsIndexRoute =
  DashboardLeadsLabelsIndexRouteImport.update({
    id: '/dashboard/leads/labels/',
    path: '/dashboard/leads/labels/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLeadsListsIndexRoute =
  DashboardLeadsListsIndexRouteImport.update({
    id: '/dashboard/leads/lists/',
    path: '/dashboard/leads/lists/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLeadsListsIdIndexRoute =
  DashboardLeadsListsIdIndexRouteImport.update({
    id: '/dashboard/leads/lists/$id/',
    path: '/dashboard/leads/lists/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectsProjectIdCollaboratorsIndexRoute =
  DashboardProjectsProjectIdCollaboratorsIndexRouteImport.update({
    id: '/dashboard/projects/$projectId/collaborators/',
    path: '/dashboard/projects/$projectId/collaborators/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/campaigns/$campaignId/settings': typeof DashboardCampaignsCampaignIdSettingsRoute
  '/dashboard/campaigns/$campaignId/': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/leads/labels/': typeof DashboardLeadsLabelsIndexRoute
  '/dashboard/leads/lists/': typeof DashboardLeadsListsIndexRoute
  '/dashboard/leads/lists/$id/': typeof DashboardLeadsListsIdIndexRoute
  '/dashboard/projects/$projectId/collaborators/': typeof DashboardProjectsProjectIdCollaboratorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/campaigns/$campaignId/settings': typeof DashboardCampaignsCampaignIdSettingsRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/leads/labels': typeof DashboardLeadsLabelsIndexRoute
  '/dashboard/leads/lists': typeof DashboardLeadsListsIndexRoute
  '/dashboard/leads/lists/$id': typeof DashboardLeadsListsIdIndexRoute
  '/dashboard/projects/$projectId/collaborators': typeof DashboardProjectsProjectIdCollaboratorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/campaigns/$campaignId/settings': typeof DashboardCampaignsCampaignIdSettingsRoute
  '/dashboard/campaigns/$campaignId/': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/leads/labels/': typeof DashboardLeadsLabelsIndexRoute
  '/dashboard/leads/lists/': typeof DashboardLeadsListsIndexRoute
  '/dashboard/leads/lists/$id/': typeof DashboardLeadsListsIdIndexRoute
  '/dashboard/projects/$projectId/collaborators/': typeof DashboardProjectsProjectIdCollaboratorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/dashboard/campaigns/'
    | '/dashboard/projects/'
    | '/dashboard/campaigns/$campaignId/settings'
    | '/dashboard/campaigns/$campaignId/'
    | '/dashboard/leads/labels/'
    | '/dashboard/leads/lists/'
    | '/dashboard/leads/lists/$id/'
    | '/dashboard/projects/$projectId/collaborators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/dashboard/projects'
    | '/dashboard/campaigns/$campaignId/settings'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/leads/labels'
    | '/dashboard/leads/lists'
    | '/dashboard/leads/lists/$id'
    | '/dashboard/projects/$projectId/collaborators'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/dashboard/campaigns/'
    | '/dashboard/projects/'
    | '/dashboard/campaigns/$campaignId/settings'
    | '/dashboard/campaigns/$campaignId/'
    | '/dashboard/leads/labels/'
    | '/dashboard/leads/lists/'
    | '/dashboard/leads/lists/$id/'
    | '/dashboard/projects/$projectId/collaborators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardCampaignsCampaignIdSettingsRoute: typeof DashboardCampaignsCampaignIdSettingsRoute
  DashboardCampaignsCampaignIdIndexRoute: typeof DashboardCampaignsCampaignIdIndexRoute
  DashboardLeadsLabelsIndexRoute: typeof DashboardLeadsLabelsIndexRoute
  DashboardLeadsListsIndexRoute: typeof DashboardLeadsListsIndexRoute
  DashboardLeadsListsIdIndexRoute: typeof DashboardLeadsListsIdIndexRoute
  DashboardProjectsProjectIdCollaboratorsIndexRoute: typeof DashboardProjectsProjectIdCollaboratorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/dashboard/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/$campaignId/': {
      id: '/dashboard/campaigns/$campaignId/'
      path: '/dashboard/campaigns/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId/'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/$campaignId/settings': {
      id: '/dashboard/campaigns/$campaignId/settings'
      path: '/dashboard/campaigns/$campaignId/settings'
      fullPath: '/dashboard/campaigns/$campaignId/settings'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/labels/': {
      id: '/dashboard/leads/labels/'
      path: '/dashboard/leads/labels'
      fullPath: '/dashboard/leads/labels/'
      preLoaderRoute: typeof DashboardLeadsLabelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/lists/': {
      id: '/dashboard/leads/lists/'
      path: '/dashboard/leads/lists'
      fullPath: '/dashboard/leads/lists/'
      preLoaderRoute: typeof DashboardLeadsListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/lists/$id/': {
      id: '/dashboard/leads/lists/$id/'
      path: '/dashboard/leads/lists/$id'
      fullPath: '/dashboard/leads/lists/$id/'
      preLoaderRoute: typeof DashboardLeadsListsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId/collaborators/': {
      id: '/dashboard/projects/$projectId/collaborators/'
      path: '/dashboard/projects/$projectId/collaborators'
      fullPath: '/dashboard/projects/$projectId/collaborators/'
      preLoaderRoute: typeof DashboardProjectsProjectIdCollaboratorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardCampaignsCampaignIdSettingsRoute:
    DashboardCampaignsCampaignIdSettingsRoute,
  DashboardCampaignsCampaignIdIndexRoute:
    DashboardCampaignsCampaignIdIndexRoute,
  DashboardLeadsLabelsIndexRoute: DashboardLeadsLabelsIndexRoute,
  DashboardLeadsListsIndexRoute: DashboardLeadsListsIndexRoute,
  DashboardLeadsListsIdIndexRoute: DashboardLeadsListsIdIndexRoute,
  DashboardProjectsProjectIdCollaboratorsIndexRoute:
    DashboardProjectsProjectIdCollaboratorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
